### ISSUE TITLE
gopls: Needs to pass GOPATH and GOROOT into the container

### ISSUE THREAD

**Issue by nogweii** [lspcontainers/lspcontainers.nvim#14]
`$GOPATH` is a colon separated list of directories that gopls will scan for code completion. The first user-writable directory is the place where `go get` will download libraries into.

`$GOROOT` is the system path and contains the stdlib I think. Probably not needed for the containers.

**Comment by erikreinert** [comment]
This was not resolved - I had to add some more work in this issue #54 but am now able to see system and installed packages.

There is ONE caveat here - we are running the LSP as `root` and it REQUIRES us to update the file system. Because of this new files are written to the filesystem with `root` permissions.

We have a way to determine which OS you're on right now for Podman - we may want to reuse this logic to replicate passing down user ID and group ID to the container. This will be the case for ANY language server that needs to update the hosts files.
