### ISSUE TITLE
Rust language server readonly fileserver

### ISSUE THREAD

**Issue by 407529** [lspcontainers/lspcontainers.nvim#50]
When I was trying to work with the rust language server. I got an error in which I was told I was working on a read only file system.
![_00004](https://user-images.githubusercontent.com/55490231/144753901-05344892-7fdf-4038-b153-b163c98052f1.png)
However when executing the same command on my file system it executes perfectly fine.
![_00005](https://user-images.githubusercontent.com/55490231/144753934-b958e154-a243-4c50-b7f7-783ca085c6c4.png)
Help is appreciated.

**Comment by erikreinert** [comment]
We not longer do `readonly` by default - that was changed with this PR #54. You should be able to sync the latest version of `lspcontainers` and see it work. I also updated the `rust_analyzer` to `2022-01-17`.

Let me know if you're still having issues - otherwise I'll close this next time I get around to it.

**Comment by 407529** [comment]
It was fixed however the fix revealed a new issue. I will open a new issue for this one and close this.
